title: Mario Liebenberg
author: Mario Liebenberg
email: mario.liebenberg@hotmail.com
description: > # this means to ignore newlines until "baseurl:"
  Basic information regarding Mario Liebenberg
# social links
twitter_username: mario_cod3
github_username:  MarioCode13

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima
